baseURL = "https://kpop-mirek.pages.dev/"
theme = "blowfish"
defaultContentLanguage = "cs"
title = "NEO HWARANG"

[params]
    colorScheme = "blowfish"
    defaultAppearance = "dark"
    showText = true
    description = "Tuto stránku jsem vytvořil jako místo, kde můžu sdílet svou cestu, chyby i úspěchy."
    # Tady natvrdo vypínáme ty problematické autory:
    article = { showAuthor = false, showAuthorsBadges = false, showAuthorBottom = false }

[taxonomies]
    tag = "tags"
    category = "categories"

[build]
    writeStats = true